### ISSUE TITLE
[Front] Vanilla flavor

### ISSUE THREAD

**Issue by NicolasLeRoux** [NicolasLeRoux/rpaswui#6]
## Goals

Trouver comment construire l'application en utilisant (presque) uniquement du vanilla. Les polyfills de feature présent dans le repo du [TC39](https://github.com/tc39/proposals) sont autorisées...

**Comment by gregorybarale** [comment]
Concernant les features [TC39](https://github.com/tc39/proposals) que l'ont utilise, minimum quel stage? Par exemple, Observable ou promesse?
